name: Build e Deploy FinanceHub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Teste de login GHCR
        run: |
          echo "${{ secrets.PAT_TOKEN }}" | docker login ghcr.io -u pno-ontec --password-stdin
          echo "Login OK"
          docker pull hello-world
          docker tag hello-world ghcr.io/pno-ontec/financehub:test
          docker push ghcr.io/pno-ontec/financehub:test
          echo "Push teste OK"
